# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74e47e475d3940700fa1f64ab24b8b8a832577455bba211e5049517877e71f75131c65c3b3cd9825ceead8f93f10889a746ef921f44744d42e254650990dfef6

test:
  secret_key_base: 16ca2bcb1c467b213edd01265b49ea87017630e475c32f6a4d6e6bf88da41900ce366a01b7b2cf023670d55227f47571167d29cc9e6d4895cc9bd7698abd4b03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
